carbon:
  rss:
    - https://climate.ec.europa.eu/news_en
    - https://unfccc.int/rss.xml
  html:
    - https://icapcarbonaction.com/en/news
    - https://www.gov.uk/government/announcements

ai:
  rss:
    - https://deepmind.google/discover/blog/rss/
    - https://openai.com/blog/rss/
  html:
    - https://digital-strategy.ec.europa.eu/en/news
    - https://www.aisi.gov.uk/news

crypto:
  rss:
    - https://www.coindesk.com/arc/outboundfeeds/rss/
  html:
    - https://www.fca.org.uk/news

linkedin_public_posts: []
