carbon:
  rss:
    - https://climate.ec.europa.eu/news_en        # European Commission Climate (free)
    - https://unfccc.int/rss.xml                  # UNFCCC newsroom RSS
  html:
    - https://icapcarbonaction.com/en/news        # ICAP news (free list page)
    - https://www.gov.uk/government/announcements # UK govt announcements (free)

ai:
  rss:
    - https://deepmind.google/discover/blog/rss/  # DeepMind blog RSS (free)
    - https://openai.com/blog/rss/                # OpenAI blog RSS (free)
  html:
    - https://digital-strategy.ec.europa.eu/en/news  # EU AI news (free)
    - https://www.aisi.gov.uk/news                 # UK AI Safety Institute news (free)

crypto:
  rss:
    - https://www.coindesk.com/arc/outboundfeeds/rss/  # CoinDesk RSS (free)
  html:
    - https://www.fca.org.uk/news                      # UK FCA news (free)

linkedin_public_posts:
  # Optional: add public LinkedIn post URLs you want included (only if viewable without login).
  - https://www.linkedin.com/posts/EXAMPLE_PUBLIC_POST
