name: Daily Telegram News

on:
  schedule:
    - cron: "30 6 * * *"  # 06:30 UTC
    - cron: "30 7 * * *"  # 07:30 UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: daily-news
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot (sends only at 07:30 London or if 'update' was sent)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
